//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resources.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resources.Api.ResponseMessages", typeof(ResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied..
        /// </summary>
        public static string AccountsAccessDenied {
            get {
                return ResourceManager.GetString("AccountsAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail already exists. Please enter a different e-mail..
        /// </summary>
        public static string AccountsEmailAlreadyExists {
            get {
                return ResourceManager.GetString("AccountsEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email and confirmation email do not match..
        /// </summary>
        public static string AccountsEmailsDoesNotMatch {
            get {
                return ResourceManager.GetString("AccountsEmailsDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid contact person name..
        /// </summary>
        public static string AccountsInvalidContactPerson {
            get {
                return ResourceManager.GetString("AccountsInvalidContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail format..
        /// </summary>
        public static string AccountsInvalidEmail {
            get {
                return ResourceManager.GetString("AccountsInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid old password..
        /// </summary>
        public static string AccountsInvalidOldPassword {
            get {
                return ResourceManager.GetString("AccountsInvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid security token..
        /// </summary>
        public static string AccountsInvalidToken {
            get {
                return ResourceManager.GetString("AccountsInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid security token secret..
        /// </summary>
        public static string AccountsInvalidTokenSecret {
            get {
                return ResourceManager.GetString("AccountsInvalidTokenSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string AccountsInvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("AccountsInvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string AccountsPasswordsDoesNotMatch {
            get {
                return ResourceManager.GetString("AccountsPasswordsDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with this email address..
        /// </summary>
        public static string AccountsUserWithEmailNotFound {
            get {
                return ResourceManager.GetString("AccountsUserWithEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad gateway..
        /// </summary>
        public static string BadGateway {
            get {
                return ResourceManager.GetString("BadGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request..
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified entity already exists..
        /// </summary>
        public static string EntityAlreadyExists {
            get {
                return ResourceManager.GetString("EntityAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request entity too large..
        /// </summary>
        public static string EntityTooLarge {
            get {
                return ResourceManager.GetString("EntityTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid product name..
        /// </summary>
        public static string ExternalVideoInvalidProduct {
            get {
                return ResourceManager.GetString("ExternalVideoInvalidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video URI..
        /// </summary>
        public static string ExternalVideoInvalidVideoUri {
            get {
                return ResourceManager.GetString("ExternalVideoInvalidVideoUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address required..
        /// </summary>
        public static string FeedbackEmailRequired {
            get {
                return ResourceManager.GetString("FeedbackEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail format..
        /// </summary>
        public static string FeedbackInvalidEmail {
            get {
                return ResourceManager.GetString("FeedbackInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback message required..
        /// </summary>
        public static string FeedbackMessageRequired {
            get {
                return ResourceManager.GetString("FeedbackMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name required..
        /// </summary>
        public static string FeedbackNameRequired {
            get {
                return ResourceManager.GetString("FeedbackNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file..
        /// </summary>
        public static string FileInvalidFile {
            get {
                return ResourceManager.GetString("FileInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format..
        /// </summary>
        public static string FileInvalidFormat {
            get {
                return ResourceManager.GetString("FileInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name..
        /// </summary>
        public static string FileInvalidName {
            get {
                return ResourceManager.GetString("FileInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden access to this resource..
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal server error occurred. Please try again later..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address..
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audio bitrate..
        /// </summary>
        public static string InvalidAudioBitrate {
            get {
                return ResourceManager.GetString("InvalidAudioBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audio channels count..
        /// </summary>
        public static string InvalidAudioChannels {
            get {
                return ResourceManager.GetString("InvalidAudioChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audio codec..
        /// </summary>
        public static string InvalidAudioCodec {
            get {
                return ResourceManager.GetString("InvalidAudioCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audio streams count..
        /// </summary>
        public static string InvalidAudioStreamsCount {
            get {
                return ResourceManager.GetString("InvalidAudioStreamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid company name..
        /// </summary>
        public static string InvalidCompanyName {
            get {
                return ResourceManager.GetString("InvalidCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid media..
        /// </summary>
        public static string InvalidMedia {
            get {
                return ResourceManager.GetString("InvalidMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid media container..
        /// </summary>
        public static string InvalidMediaContainer {
            get {
                return ResourceManager.GetString("InvalidMediaContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request body. Required multipart/form-data..
        /// </summary>
        public static string InvalidMultipartBody {
            get {
                return ResourceManager.GetString("InvalidMultipartBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid query options..
        /// </summary>
        public static string InvalidQueryOptions {
            get {
                return ResourceManager.GetString("InvalidQueryOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource state..
        /// </summary>
        public static string InvalidResourceState {
            get {
                return ResourceManager.GetString("InvalidResourceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid subscription type..
        /// </summary>
        public static string InvalidSubscriptionType {
            get {
                return ResourceManager.GetString("InvalidSubscriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video bitrate..
        /// </summary>
        public static string InvalidVideoBitrate {
            get {
                return ResourceManager.GetString("InvalidVideoBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video codec..
        /// </summary>
        public static string InvalidVideoCodec {
            get {
                return ResourceManager.GetString("InvalidVideoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video frame rate..
        /// </summary>
        public static string InvalidVideoFrameRate {
            get {
                return ResourceManager.GetString("InvalidVideoFrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video height..
        /// </summary>
        public static string InvalidVideoHeight {
            get {
                return ResourceManager.GetString("InvalidVideoHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video streams count..
        /// </summary>
        public static string InvalidVideoStreamsCount {
            get {
                return ResourceManager.GetString("InvalidVideoStreamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video width..
        /// </summary>
        public static string InvalidVideoWidth {
            get {
                return ResourceManager.GetString("InvalidVideoWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Not Allowed.
        /// </summary>
        public static string MethodNotAllowed {
            get {
                return ResourceManager.GetString("MethodNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not acceptable format..
        /// </summary>
        public static string NotAcceptable {
            get {
                return ResourceManager.GetString("NotAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid poject identifier..
        /// </summary>
        public static string NotificationInvalidProjectId {
            get {
                return ResourceManager.GetString("NotificationInvalidProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment required..
        /// </summary>
        public static string PaymentRequired {
            get {
                return ResourceManager.GetString("PaymentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image file..
        /// </summary>
        public static string ProfileInvalidAvatarFile {
            get {
                return ResourceManager.GetString("ProfileInvalidAvatarFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid city..
        /// </summary>
        public static string ProfileInvalidCity {
            get {
                return ResourceManager.GetString("ProfileInvalidCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid company name..
        /// </summary>
        public static string ProfileInvalidCompanyName {
            get {
                return ResourceManager.GetString("ProfileInvalidCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid contact address..
        /// </summary>
        public static string ProfileInvalidContactAddress {
            get {
                return ResourceManager.GetString("ProfileInvalidContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid country..
        /// </summary>
        public static string ProfileInvalidCountry {
            get {
                return ResourceManager.GetString("ProfileInvalidCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Employer Identification Number..
        /// </summary>
        public static string ProfileInvalidEin {
            get {
                return ResourceManager.GetString("ProfileInvalidEin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number..
        /// </summary>
        public static string ProfileInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("ProfileInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time zone..
        /// </summary>
        public static string ProfileInvalidTimeZone {
            get {
                return ResourceManager.GetString("ProfileInvalidTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username..
        /// </summary>
        public static string ProfileInvalidUserName {
            get {
                return ResourceManager.GetString("ProfileInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid zip code..
        /// </summary>
        public static string ProfileInvalidZipCode {
            get {
                return ResourceManager.GetString("ProfileInvalidZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project access value..
        /// </summary>
        public static string ProjectInvalidAccess {
            get {
                return ResourceManager.GetString("ProjectInvalidAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid avsx file..
        /// </summary>
        public static string ProjectInvalidAvsxFile {
            get {
                return ResourceManager.GetString("ProjectInvalidAvsxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project description..
        /// </summary>
        public static string ProjectInvalidDescription {
            get {
                return ResourceManager.GetString("ProjectInvalidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project identifier..
        /// </summary>
        public static string ProjectInvalidId {
            get {
                return ResourceManager.GetString("ProjectInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project name..
        /// </summary>
        public static string ProjectInvalidName {
            get {
                return ResourceManager.GetString("ProjectInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid public property value..
        /// </summary>
        public static string ProjectInvalidPublicValue {
            get {
                return ResourceManager.GetString("ProjectInvalidPublicValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid screenshot file..
        /// </summary>
        public static string ProjectInvalidScreenshotFile {
            get {
                return ResourceManager.GetString("ProjectInvalidScreenshotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project subtype..
        /// </summary>
        public static string ProjectInvalidSubtype {
            get {
                return ResourceManager.GetString("ProjectInvalidSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project type..
        /// </summary>
        public static string ProjectInvalidType {
            get {
                return ResourceManager.GetString("ProjectInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video file..
        /// </summary>
        public static string ProjectInvalidVideoFile {
            get {
                return ResourceManager.GetString("ProjectInvalidVideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video hash..
        /// </summary>
        public static string ProjectInvalidVideoHash {
            get {
                return ResourceManager.GetString("ProjectInvalidVideoHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has timed out..
        /// </summary>
        public static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource is no longer available..
        /// </summary>
        public static string ResourceGone {
            get {
                return ResourceManager.GetString("ResourceGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource is not found..
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is currently under maintenance..
        /// </summary>
        public static string ServiceUnavailable {
            get {
                return ResourceManager.GetString("ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hostname..
        /// </summary>
        public static string SubscriptionInvalidSiteHostname {
            get {
                return ResourceManager.GetString("SubscriptionInvalidSiteHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid site name..
        /// </summary>
        public static string SubscriptionInvalidSiteName {
            get {
                return ResourceManager.GetString("SubscriptionInvalidSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid payment amount..
        /// </summary>
        public static string SubscriptionPaymentInvalidAmount {
            get {
                return ResourceManager.GetString("SubscriptionPaymentInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests..
        /// </summary>
        public static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid status message..
        /// </summary>
        public static string TwitterInvalidStatus {
            get {
                return ResourceManager.GetString("TwitterInvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string TwitterInvalidToken {
            get {
                return ResourceManager.GetString("TwitterInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token secret..
        /// </summary>
        public static string TwitterInvalidTokenSecret {
            get {
                return ResourceManager.GetString("TwitterInvalidTokenSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource requires user authentication..
        /// </summary>
        public static string UnathorizedRequest {
            get {
                return ResourceManager.GetString("UnathorizedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {2} and {1} characters long..
        /// </summary>
        public static string ValidationValueMustBeInRange {
            get {
                return ResourceManager.GetString("ValidationValueMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must not be greater than {1} characters long..
        /// </summary>
        public static string ValidationValueMustNotBeGreaterThan {
            get {
                return ResourceManager.GetString("ValidationValueMustNotBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid widget identifier..
        /// </summary>
        public static string WidgetInvalidId {
            get {
                return ResourceManager.GetString("WidgetInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid widget data..
        /// </summary>
        public static string WidgetItemInvalidContent {
            get {
                return ResourceManager.GetString("WidgetItemInvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid widget item id..
        /// </summary>
        public static string WidgetItemInvalidId {
            get {
                return ResourceManager.GetString("WidgetItemInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid widget name..
        /// </summary>
        public static string WidgetItemInvalidName {
            get {
                return ResourceManager.GetString("WidgetItemInvalidName", resourceCulture);
            }
        }
    }
}
