// Copyright (c) Clickberry, Inc. All rights reserved.
// Licensed under the GNU GENERAL PUBLIC LICENSE Version 3. See License.txt in the project root for license information.

angular.module('resources.common', []).factory('resources', function () {

    var resources = window.cb && window.cb.resources ? window.cb.resources : {};

    resources.clientCountries = {
        "United States": "us",
        'Afghanistan':'af', 
        'Albania':'al', 
        'Algeria':'dz', 
        'Argentina':'ar', 
        'Armenia':'am', 
        'Australia':'au', 
        'Austria':'at', 
        'Azerbaijan':'az', 
        'Bahrain':'bh', 
        'Bangladesh':'bd', 
        'Belarus':'by', 
        'Belgium':'be', 
        'Belize':'bz', 
        'Venezuela':'ve', 
        'Bolivia':'bo', 
        'Bosnia and Herzegovina':'ba', 
        'Botswana':'bw', 
        'Brazil':'br', 
        'Brunei Darussalam':'bn', 
        'Bulgaria':'bg', 
        'Cambodia':'kh', 
        'Cameroon':'cm', 
        'Canada':'ca', 
        'Chile':'cl', 
        'China':'cn', 
        'Colombia':'co', 
        'Congo [DRC]':'cd', 
        'Costa Rica':'cr', 
        'Croatia':'hr', 
        'Czech Republic':'cz', 
        'Denmark':'dk', 
        'Dominican Republic':'do', 
        'Ecuador':'ec', 
        'Egypt':'eg', 
        'El Salvador':'sv', 
        'Eritrea':'er', 
        'Estonia':'ee', 
        'Ethiopia':'et', 
        'Faroe Islands':'fo', 
        'Finland':'fi', 
        'France':'fr', 
        'Georgia':'ge', 
        'Germany':'de', 
        'Greece':'gr', 
        'Greenland':'gl', 
        'Guatemala':'gt', 
        'Haiti':'ht', 
        'Honduras':'hn', 
        'Hong Kong SAR':'hk', 
        'Hungary':'hu', 
        'Iceland':'is', 
        'India':'in', 
        'Indonesia':'id', 
        'Iran':'ir', 
        'Iraq':'iq', 
        'Ireland':'ie', 
        'Israel':'il', 
        'Italy':'it', 
        'Ivory Coast':'ci', 
        'Jamaica':'jm', 
        'Japan':'jp', 
        'Jordan':'jo', 
        'Kazakhstan':'kz', 
        'Kenya':'ke', 
        'Korea':'kr', 
        'Kuwait':'kw', 
        'Kyrgyzstan':'kg', 
        'Lao PDR':'la', 
        'Latvia':'lv', 
        'Lebanon':'lb', 
        'Libya':'ly', 
        'Liechtenstein':'li', 
        'Lithuania':'lt', 
        'Luxembourg':'lu', 
        'Macao SAR':'mo', 
        'Macedonia':'mk', 
        'Malaysia':'my', 
        'Maldives':'mv', 
        'Mali':'ml', 
        'Malta':'mt', 
        'Mexico':'mx', 
        'Moldova':'md', 
        'Mongolia':'mn', 
        'Montenegro':'me', 
        'Morocco':'ma', 
        'Myanmar':'mm', 
        'Nepal':'np', 
        'Netherlands':'nl', 
        'New Zealand':'nz', 
        'Nicaragua':'ni', 
        'Nigeria':'ng', 
        'Norway':'no', 
        'Oman':'om', 
        'Pakistan':'pk', 
        'Panama':'pa', 
        'Paraguay':'py', 
        'Peru':'pe', 
        'Philippines':'ph', 
        'Poland':'pl', 
        'Portugal':'pt', 
        'Monaco':'mc', 
        'Puerto Rico':'pr', 
        'Qatar':'qa', 
        'Réunion':'re', 
        'Romania':'ro', 
        'Russia':'ru', 
        'Rwanda':'rw', 
        'Saudi Arabia':'sa', 
        'Senegal':'sn', 
        'Serbia':'rs', 
        'Singapore':'sg', 
        'Slovakia':'sk', 
        'Slovenia':'si', 
        'Somalia':'so', 
        'South Africa':'za', 
        'Spain':'es', 
        'Sri Lanka':'lk', 
        'Sweden':'se', 
        'Switzerland':'ch', 
        'Syria':'sy', 
        'Taiwan':'tw', 
        'Tajikistan':'tj', 
        'Thailand':'th', 
        'Trinidad and Tobago':'tt', 
        'Tunisia':'tn', 
        'Turkey':'tr', 
        'Turkmenistan':'tm', 
        'U.A.E.':'ae', 
        'Ukraine':'ua', 
        'United Kingdom':'gb', 
        'Uruguay':'uy', 
        'Uzbekistan':'uz', 
        'Vietnam':'vn', 
        'Yemen':'ye', 
        'Zimbabwe':'zw',
    };

    resources.socials = [];

    return resources;

});