//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resources.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InterfaceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InterfaceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resources.Web.InterfaceMessages", typeof(InterfaceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Clickberry.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string AccountConfirmPassword {
            get {
                return ResourceManager.GetString("AccountConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string AccountEmail {
            get {
                return ResourceManager.GetString("AccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AccountPassword {
            get {
                return ResourceManager.GetString("AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me logged in.
        /// </summary>
        public static string AccountRememberMe {
            get {
                return ResourceManager.GetString("AccountRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string AccountUserName {
            get {
                return ResourceManager.GetString("AccountUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete your registration - Clickberry.
        /// </summary>
        public static string CompleteRegistrationTitle {
            get {
                return ResourceManager.GetString("CompleteRegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not sent.
        /// </summary>
        public static string ExamplesPushNotSent {
            get {
                return ResourceManager.GetString("ExamplesPushNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string ExamplesPushSent {
            get {
                return ResourceManager.GetString("ExamplesPushSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Video.
        /// </summary>
        public static string ExamplesVideoPrivate {
            get {
                return ResourceManager.GetString("ExamplesVideoPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Video.
        /// </summary>
        public static string ExamplesVideoPublic {
            get {
                return ResourceManager.GetString("ExamplesVideoPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail*.
        /// </summary>
        public static string FeedbackEmail {
            get {
                return ResourceManager.GetString("FeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while sending your feedback message. Please, try again later..
        /// </summary>
        public static string FeedbackError {
            get {
                return ResourceManager.GetString("FeedbackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message...*.
        /// </summary>
        public static string FeedbackMessage {
            get {
                return ResourceManager.GetString("FeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name*.
        /// </summary>
        public static string FeedbackName {
            get {
                return ResourceManager.GetString("FeedbackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string FeedbackPhone {
            get {
                return ResourceManager.GetString("FeedbackPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string FeedbackSubmit {
            get {
                return ResourceManager.GetString("FeedbackSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback message has been successfully sent to administrator. Thank you!.
        /// </summary>
        public static string FeedbackSuccess {
            get {
                return ResourceManager.GetString("FeedbackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014 © Clickberry, Inc.&lt;br/&gt;
        ///All rights reserved..
        /// </summary>
        public static string LayoutCopyright {
            get {
                return ResourceManager.GetString("LayoutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string LayoutLicenseAgreement {
            get {
                return ResourceManager.GetString("LayoutLicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LayoutLogoff {
            get {
                return ResourceManager.GetString("LayoutLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LayoutLogon {
            get {
                return ResourceManager.GetString("LayoutLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string LayoutSupport {
            get {
                return ResourceManager.GetString("LayoutSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string MenuAdministration {
            get {
                return ResourceManager.GetString("MenuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string MenuAllClients {
            get {
                return ResourceManager.GetString("MenuAllClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string MenuAllRoles {
            get {
                return ResourceManager.GetString("MenuAllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string MenuAllUsers {
            get {
                return ResourceManager.GetString("MenuAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Videos.
        /// </summary>
        public static string MenuAllVideos {
            get {
                return ResourceManager.GetString("MenuAllVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor&apos;s pick.
        /// </summary>
        public static string MenuEditorsPick {
            get {
                return ResourceManager.GetString("MenuEditorsPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string MenuExamples {
            get {
                return ResourceManager.GetString("MenuExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string MenuLatest {
            get {
                return ResourceManager.GetString("MenuLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My likes.
        /// </summary>
        public static string MenuLikes {
            get {
                return ResourceManager.GetString("MenuLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MenuProfile {
            get {
                return ResourceManager.GetString("MenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string MenuStats {
            get {
                return ResourceManager.GetString("MenuStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Subscriptions.
        /// </summary>
        public static string MenuSubscriptions {
            get {
                return ResourceManager.GetString("MenuSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string MenuTrends {
            get {
                return ResourceManager.GetString("MenuTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My snaps.
        /// </summary>
        public static string MenuVideos {
            get {
                return ResourceManager.GetString("MenuVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string MenuWidgets {
            get {
                return ResourceManager.GetString("MenuWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on Clickberry Storage.
        /// </summary>
        public static string OnClickBerryStorage {
            get {
                return ResourceManager.GetString("OnClickBerryStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used space.
        /// </summary>
        public static string ProfileUsedSpace {
            get {
                return ResourceManager.GetString("ProfileUsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string ProfileUsedSpaceOf {
            get {
                return ResourceManager.GetString("ProfileUsedSpaceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDKs.
        /// </summary>
        public static string Sdk {
            get {
                return ResourceManager.GetString("Sdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Browser.
        /// </summary>
        public static string UnsupportedBrowser {
            get {
                return ResourceManager.GetString("UnsupportedBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy HTML code.
        /// </summary>
        public static string VideoCopyHtmlCode {
            get {
                return ResourceManager.GetString("VideoCopyHtmlCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can copy the HTML code below and publish your interactive video on your page, blog or on any place on the web..
        /// </summary>
        public static string VideoCopyHtmlCodeHint {
            get {
                return ResourceManager.GetString("VideoCopyHtmlCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Upload.
        /// </summary>
        public static string VideoDateUpload {
            get {
                return ResourceManager.GetString("VideoDateUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Video.
        /// </summary>
        public static string VideoDelete {
            get {
                return ResourceManager.GetString("VideoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are processing video....
        /// </summary>
        public static string VideoEncodingInProgress {
            get {
                return ResourceManager.GetString("VideoEncodingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a video tag of your own, click {0} to download a new browser extension..
        /// </summary>
        public static string VideoExtensionAddonTooltip {
            get {
                return ResourceManager.GetString("VideoExtensionAddonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video has not been uploaded yet..
        /// </summary>
        public static string VideoNotUploaded {
            get {
                return ResourceManager.GetString("VideoNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make this video visible to others.
        /// </summary>
        public static string VideoPublicVisibility {
            get {
                return ResourceManager.GetString("VideoPublicVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search video.
        /// </summary>
        public static string VideosSearch {
            get {
                return ResourceManager.GetString("VideosSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No videos found..
        /// </summary>
        public static string VideosSearchNoResults {
            get {
                return ResourceManager.GetString("VideosSearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more videos.
        /// </summary>
        public static string VideosShowMore {
            get {
                return ResourceManager.GetString("VideosShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string WelcomeCreate {
            get {
                return ResourceManager.GetString("WelcomeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making a video interactive is easy with Clickberry. Simply grab a video and pull it into Clickberry to use the drag-and-drop tools. It&apos;s fast, easy and fun..
        /// </summary>
        public static string WelcomeCreateHint {
            get {
                return ResourceManager.GetString("WelcomeCreateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string WelcomeForgotPassword {
            get {
                return ResourceManager.GetString("WelcomeForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string WelcomeShare {
            get {
                return ResourceManager.GetString("WelcomeShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then you can share your interactive video on the web in just a few seconds..
        /// </summary>
        public static string WelcomeShareHint {
            get {
                return ResourceManager.GetString("WelcomeShareHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or connect using.
        /// </summary>
        public static string WelcomeSocial {
            get {
                return ResourceManager.GetString("WelcomeSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clickberry Online Storage.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string WelcomeUpload {
            get {
                return ResourceManager.GetString("WelcomeUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you made your video interactive click “upload” and we&apos;ll host it for free on Clickberry Online Storage..
        /// </summary>
        public static string WelcomeUploadHint {
            get {
                return ResourceManager.GetString("WelcomeUploadHint", resourceCulture);
            }
        }
    }
}
