//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body marginheight=&quot;0&quot; marginwidth=&quot;0&quot; leftmargin=&quot;0&quot; topmargin=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;
        ///          style=&quot;font-family: Arial, Helvetica, sans-serif;&quot;&gt;
        ///        &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AbuseReported {
            get {
                return ResourceManager.GetString("AbuseReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body marginheight=&quot;0&quot; marginwidth=&quot;0&quot; leftmargin=&quot;0&quot; topmargin=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;
        ///          style=&quot;font-family: Arial, Helvetica, sans-serif;&quot;&gt;
        ///        &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ClientActivation {
            get {
                return ResourceManager.GetString("ClientActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body marginheight=&quot;0&quot; marginwidth=&quot;0&quot; leftmargin=&quot;0&quot; topmargin=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;
        ///          style=&quot;font-family: Arial, Helvetica, sans-serif;&quot;&gt;
        ///        &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentCompleted {
            get {
                return ResourceManager.GetString("PaymentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body marginheight=&quot;0&quot; marginwidth=&quot;0&quot; leftmargin=&quot;0&quot; topmargin=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;
        ///          style=&quot;font-family: Arial, Helvetica, sans-serif;&quot;&gt;
        ///        &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body marginheight=&quot;0&quot; marginwidth=&quot;0&quot; leftmargin=&quot;0&quot; topmargin=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;
        ///          style=&quot;font-family: Arial, Helvetica, sans-serif;&quot;&gt;
        ///        &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentRefunded {
            get {
                return ResourceManager.GetString("PaymentRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body marginheight=&quot;0&quot; marginwidth=&quot;0&quot; leftmargin=&quot;0&quot; topmargin=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td align=&quot;center&quot; valign=&quot;top&quot;&gt;
        ///                    &lt;table border=&quot;0&quot; ce [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProjectFirstCic {
            get {
                return ResourceManager.GetString("ProjectFirstCic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Email&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body marginheight=&quot;0&quot; marginwidth=&quot;0&quot; leftmargin=&quot;0&quot; topmargin=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td align=&quot;cen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProjectFirstTagger {
            get {
                return ResourceManager.GetString("ProjectFirstTagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body marginheight=&quot;0&quot; marginwidth=&quot;0&quot; leftmargin=&quot;0&quot; topmargin=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;
        ///      style=&quot;font-family: Arial, Helvetica, sans-serif;&quot;&gt;
        ///    &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UserRecovery {
            get {
                return ResourceManager.GetString("UserRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Email&lt;/title&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body marginheight=&quot;0&quot; marginwidth=&quot;0&quot; leftmargin=&quot;0&quot; topmargin=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;&gt;
        ///&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td align=&quot;center&quot; valign=&quot;top&quot;&gt;&lt;table borde [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UserRegistration {
            get {
                return ResourceManager.GetString("UserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Email&lt;/title&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body marginheight=&quot;0&quot; marginwidth=&quot;0&quot; leftmargin=&quot;0&quot; topmargin=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;&gt;
        ///&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td align=&quot;center&quot; valign=&quot;top&quot;&gt;&lt;table borde [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UserRegistrationImageshack {
            get {
                return ResourceManager.GetString("UserRegistrationImageshack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body marginheight=&quot;0&quot; marginwidth=&quot;0&quot; leftmargin=&quot;0&quot; topmargin=&quot;0&quot; bgcolor=&quot;#FAFAFA&quot;
        ///          style=&quot;font-family: Arial, Helvetica, sans-serif;&quot;&gt;
        ///        &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VideoCommentNotification {
            get {
                return ResourceManager.GetString("VideoCommentNotification", resourceCulture);
            }
        }
    }
}
